### ISSUE TITLE
Uncaught Exception: Неверный товар - woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:150

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#118]
[23-Dec-2018 21:00:48 UTC] PHP Fatal error:  Uncaught Exception: Неверный товар. in /home/tvoiprot/public_html/site/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:150
Stack trace:
#0 /home/tvoiprot/public_html/site/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Product_Data_Store_CPT->read(Object(WC_Product_Simple))
#1 /home/tvoiprot/public_html/site/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(134): WC_Data_Store->read(Object(WC_Product_Simple))
#2 /home/tvoiprot/public_html/site/wp-content/plugins/woocommerce/includes/class-wc-product-simple.php(24): WC_Product->__construct(Object(WC_Product_Variation))
#3 /home/tvoiprot/public_html/site/wp-content/plugins/wooms/inc/class-products-walker.php(119): WC_Product_Simple->__construct(Object(WC_Product_Variation))
#4 /home/tvoiprot/public_html/site/wp-includes/class-wp-hook.php(286): WooMS\Products\Walker::update_product(Object(WC_Product_Variation), Array, Array)
#5 /home/tvoiprot/public_html/site/wp in /home/tvoiprot/public_html/site/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php on line 150

ХД 1629

**Comment by uptimizt** [comment]
пока нашел временное решение. 

есть риск что оно будет ломать какие то сценарии.
надо будет понаблюдать за обратной связью.
и если при текущем решении будут проблемы с обратной конвертацией вариативных в простые - придумывать какой то хитрый фильтр.

**Comment by uptimizt** [comment]
пока вроде решение рабочее. 
если будут с ним проблему, то вернемся к поиску др. решений.
