### ISSUE TITLE
PHP Fatal error если ввести не верный логин и пароль

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#123]
Надо протестировать не верный ввод имени и пароля. Плагин должен сообщать об этом в админке, а не вызывать фаталы.
```
[13-Jan-2019 15:25:10 UTC] PHP Fatal error: Uncaught Error: Class 'WooMS\Products\Exception' not found in /home/cp344624/public_html/wp-content/plugins/wooms/inc/class-products-walker.php:387
Stack trace:
#0 /home/cp344624/public_html/wp-content/plugins/wooms/inc/class-products-walker.php(304): WooMS\Products\Walker::walker()
#1 /home/cp344624/public_html/wp-includes/class-wp-hook.php(286): WooMS\Products\Walker::walker_cron_starter()
#2 /home/cp344624/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /home/cp344624/public_html/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#4 /home/cp344624/public_html/wp-cron.php(126): do_action_ref_array('wooms_cron_walk...', Array)
#5 {main}
thrown in /home/cp344624/public_html/wp-content/plugins/wooms/inc/class-products-walker.php on line 387
```

**Comment by uptimizt** [comment]
https://github.com/wpcraft-ru/wooms/commit/4a478816b9e63bcb275f22729f1f2bf172f82b3f

поправил
