### ISSUE TITLE
Ошибка при синхронизации  заказов с Моим Складом

### ISSUE THREAD

**Issue by seredniy** [wpcraft-ru/wooms#145]
```
2019-03-06T16:02:59+00:00 CRITICAL Uncaught Exception: Заказ не обновился in /home/u289081/califo.ru/www/wp-content/plugins/wooms-extra/inc/class-orders-statuses-from-moysklad.php:302
Stack trace:
#0 /home/u289081/califo.ru/www/wp-includes/rest-api/class-wp-rest-server.php(936): WooMS\Orders\Statuses_From_MoySklad::get_data_order_from_moysklad(Object(WP_REST_Request))
#1 /home/u289081/califo.ru/www/wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server->dispatch(Object(WP_REST_Request))
#2 /home/u289081/califo.ru/www/wp-includes/rest-api.php(295): WP_REST_Server->serve_request('/wooms/v1/order...')
#3 /home/u289081/califo.ru/www/wp-includes/class-wp-hook.php(286): rest_api_loaded(Object(WP))
#4 /home/u289081/califo.ru/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /home/u289081/califo.ru/www/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#6 /home/u289081/califo.ru/www/wp-includes/class-wp.php(375): do_action_ref_array('parse_request', Array)
#7 /home/u289081/califo.ru/www/wp-i в /home/u289081/califo.ru/www/wp-content/plugins/wooms-extra/inc/class-orders-statuses-from-moysklad.php на строке 302

2019-03-06T16:03:02+00:00 CRITICAL Uncaught Exception: Заказ не обновился in /home/u289081/califo.ru/www/wp-content/plugins/wooms-extra/inc/class-orders-statuses-from-moysklad.php:302
Stack trace:
#0 /home/u289081/califo.ru/www/wp-includes/rest-api/class-wp-rest-server.php(936): WooMS\Orders\Statuses_From_MoySklad::get_data_order_from_moysklad(Object(WP_REST_Request))
#1 /home/u289081/califo.ru/www/wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server->dispatch(Object(WP_REST_Request))
#2 /home/u289081/califo.ru/www/wp-includes/rest-api.php(295): WP_REST_Server->serve_request('/wooms/v1/order...')
#3 /home/u289081/califo.ru/www/wp-includes/class-wp-hook.php(286): rest_api_loaded(Object(WP))
#4 /home/u289081/califo.ru/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /home/u289081/califo.ru/www/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#6 /home/u289081/califo.ru/www/wp-includes/class-wp.php(375): do_action_ref_array('parse_request', Array)
#7 /home/u289081/califo.ru/www/wp-i в /home/u289081/califo.ru/www/wp-content/plugins/wooms-extra/inc/class-orders-statuses-from-moysklad.php на строке 302
```

**Comment by uptimizt** [comment]
Похоже на ошибку обновления статуса из Склада на Сайт. В 4.12 улучшен логгер для отслеживания такой ошибки. Скоро релиз.

А пока можно попробовать посмотреть какой статус прилетел на Сайт и какие статусы в настройках укзаны. Мб получится определить причину.

@seredniy
