### ISSUE TITLE
Ошибка при загрузке картинок

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooms#348]
fatal error
```
2020-08-23T00:00:38+00:00 CRITICAL Uncaught Error: Cannot use object of type WP_Error as array in .../httpdocs/wp-content/plugins/wooms/inc/MSImagesTrait.php:49
```

ошибка из модуля загрузки:
```
2020-07-23T00:00:17+00:00 ERROR Ошибка загрузки картинки: cURL error 7: Failed connect to storage.files.mo01.cloud.servers.com:8080; Connection refused:
http_request_failed
```

**Comment by SliceofHuman** [comment]
После апдейта всё равно ловлю fatal error

2020-08-30T12:59:11+00:00 CRITICAL Uncaught Error: Cannot use object of type WP_Error as array in /home/u167229/syndrome.sliceofart.ru/www/wp-content/plugins/wooms/inc/MSImagesTrait.php:49
Stack trace:
#0 /home/u167229/syndrome.sliceofart.ru/www/wp-content/plugins/wooms-extra/inc/ProductVariableImage.php(79): WooMS\ProductVariableImage::uploadRemoteImageAndAttach('https://online....', 6074, 'a-d-pancho-grey...')
#1 /home/u167229/syndrome.sliceofart.ru/www/wp-content/plugins/wooms-extra/inc/ProductVariableImage.php(56): WooMS\ProductVariableImage::download_img_for_product(6074)
#2 /home/u167229/syndrome.sliceofart.ru/www/wp-includes/class-wp-hook.php(287): WooMS\ProductVariableImage::walker()
#3 /home/u167229/syndrome.sliceofart.ru/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#4 /home/u167229/syndrome.sliceofart.ru/www/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#5 /home/u167229/syndrome.sliceofart.ru/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/actions/ActionScheduler_Action.php(2 в /home/u167229/syndrome.sliceofart.ru/www/wp-content/plugins/wooms/inc/MSImagesTrait.php на строке 49

**Comment by Br0dyaga** [comment]
На Ru Center https://www.nic.ru/ проблема решилась подключением услуги "Выделенный Ip адрес"
