### ISSUE TITLE
Ошибка при редактировании заказа

### ISSUE THREAD

**Issue by ne0nx** [wpcraft-ru/wooms#375]
Подробности ошибки
===================================
Ошибка с типом E_ERROR возникла на строке 988 файла /var/www/html/wp-content/plugins/wooms-extra/inc/OrderSender.php. Сообщение об ошибке: Uncaught Error: Call to a member function setTimeZone() on null in /var/www/html/wp-content/plugins/wooms-extra/inc/OrderSender.php:988
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(287): WooMS\OrderSender::add_moment()
#1 /var/www/html/wp-includes/plugin.php(206): WP_Hook->apply_filters()
#2 /var/www/html/wp-content/plugins/wooms-extra/inc/OrderSender.php(431): apply_filters()
#3 /var/www/html/wp-content/plugins/wooms-extra/inc/OrderSender.php(118): WooMS\OrderSender::send_order()
#4 /var/www/html/wp-content/plugins/wooms-extra/inc/OrderSender.php(281): WooMS\OrderSender::order_update_to_moysklad()
#5 /var/www/html/wp-includes/class-wp-hook.php(289): WooMS\OrderSender::order_update_by_hook()
#6 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#7 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action()
#8 /var/www/html/wp-includes/post.php(4249): do_action()
#9 /var/www/html/wp-includes/post.php(4354): wp_insert_post()
#10 /var/www/html/wp-admin/includes/post.php

**Comment by ne0nx** [comment]
Писал на сайте через форму. Почему нет ответа?
https://wpcraft.ru/

**Comment by ne0nx** [comment]
@uptimizt Почему не отвечаете на email? Я приобрел платную версию.
И не могу пользоваться плагином
