### ISSUE TITLE
 Class 'WooMS\AbstractWalker' not found

### ISSUE THREAD

**Issue by 4TRM** [wpcraft-ru/wooms#443]
после обновления на вукомерс 6.1.1

Fatal error: Uncaught Error: Class 'WooMS\AbstractWalker' not found in /ляляля/wp-content/plugins/wooms-extra/inc/ProductGrouped.php:10 Stack trace: #0 /ляляля/wp-content/plugins/wooms-extra/wooms-extra.php(47): require_once() #1 /ляляля/wp-includes/class-wp-hook.php(303): {closure}('') #2 /ляляля/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #3 /ляляля/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #4 /ляляля/wp-settings.php(441): do_action('plugins_loaded') #5 /ляляля/wp-config.php(96): require_once('/var/www/u11481...') #6 /ляляля/wp-load.php(50): require_once('/var/www/u11481...') #7 /ляляля/wp-admin/admin.php(34): require_once('/var/www/u11481...') #8 /var/www/u1148114/data/www/compl in /ляляля/wp-content/plugins/wooms-extra/inc/ProductGrouped.php on line 10

**Comment by 4TRM** [comment]
криво обновился woocomerce 6.1.1
